spring.application.name=fibernet

spring.datasource.url=jdbc:postgresql://localhost:5432/fibernet_web

spring.datasource.username=postgres
spring.datasource.password=kiri89730

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081